import type { PlanoConfig } from "@/lib/types";

export const PLANOS: PlanoConfig[] = [
  {
    id: "entrada",
    nome: "Entrada",
    precoMensal: 117,
    precoAnual: 97,
    economiaAnual: 240,
    tagline: "Para empresas que estão começando",
    usuarios: 1,
    armazenamento: "2 GB",
    sla: "48h",
    features: [
      { descricao: "Canal de denúncias web", disponivel: true },
      { descricao: "Triagem automática por IA", disponivel: true },
      { descricao: "Dashboard de gestão", disponivel: true },
      { descricao: "Relatórios mensais", disponivel: true },
      { descricao: "Assistente IA para gestores", disponivel: false },
      { descricao: "Múltiplos gestores", disponivel: false },
      { descricao: "Canal WhatsApp", disponivel: false },
      { descricao: "SLA prioritário 4h", disponivel: false },
      { descricao: "Unidades / multi-site", disponivel: false },
      { descricao: "White label", disponivel: false },
    ],
  },
  {
    id: "gestao",
    nome: "Gestão",
    precoMensal: 227,
    precoAnual: 197,
    economiaAnual: 360,
    tagline: "Para quem precisa de controle total",
    usuarios: 10,
    armazenamento: "20 GB",
    sla: "4h úteis",
    destaque: true,
    features: [
      { descricao: "Canal de denúncias web", disponivel: true },
      { descricao: "Triagem automática por IA", disponivel: true },
      { descricao: "Dashboard de gestão", disponivel: true },
      { descricao: "Relatórios mensais", disponivel: true },
      { descricao: "Assistente IA para gestores", disponivel: true },
      { descricao: "Múltiplos gestores (até 10)", disponivel: true },
      { descricao: "Canal WhatsApp", disponivel: false },
      { descricao: "SLA prioritário 4h", disponivel: true },
      { descricao: "Unidades / multi-site", disponivel: false },
      { descricao: "White label", disponivel: false },
    ],
  },
  {
    id: "enterprise",
    nome: "Enterprise",
    precoMensal: null,
    precoAnual: null,
    tagline: "Para grupos e organizações complexas",
    usuarios: Infinity,
    armazenamento: "Ilimitado",
    sla: "2h úteis",
    features: [
      { descricao: "Canal de denúncias web", disponivel: true },
      { descricao: "Triagem automática por IA", disponivel: true },
      { descricao: "Dashboard de gestão", disponivel: true },
      { descricao: "Relatórios mensais", disponivel: true },
      { descricao: "Assistente IA para gestores", disponivel: true },
      { descricao: "Gestores ilimitados", disponivel: true },
      { descricao: "Canal WhatsApp", disponivel: true },
      { descricao: "SLA prioritário 2h", disponivel: true },
      { descricao: "Unidades / multi-site", disponivel: true },
      { descricao: "White label", disponivel: true },
    ],
  },
];
